# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\"J\n\x0b\x43redentials\x12\x10\n\x08peerName\x18\x01 \x01(\t\x12\x17\n\x0fpuertoPservidor\x18\x02 \x01(\t\x12\x10\n\x08\x66ileName\x18\x03 \x03(\t\"+\n\x11OperationResponse\x12\x16\n\x0eserverResponse\x18\x01 \x01(\t2\xc5\x01\n\rMainFunctions\x12+\n\x05login\x12\x0c.Credentials\x1a\x12.OperationResponse\"\x00\x12,\n\x06logout\x12\x0c.Credentials\x1a\x12.OperationResponse\"\x00\x12,\n\x06search\x12\x0c.Credentials\x1a\x12.OperationResponse\"\x00\x12+\n\x05index\x12\x0c.Credentials\x1a\x12.OperationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREDENTIALS']._serialized_start=17
  _globals['_CREDENTIALS']._serialized_end=91
  _globals['_OPERATIONRESPONSE']._serialized_start=93
  _globals['_OPERATIONRESPONSE']._serialized_end=136
  _globals['_MAINFUNCTIONS']._serialized_start=139
  _globals['_MAINFUNCTIONS']._serialized_end=336
# @@protoc_insertion_point(module_scope)
